/* Three impossible finale effects: 4D projection, cyclic occlusion and recursive portals. */
(function(root){'use strict';
const PI=Math.PI,TAU=PI*2,S=Math.sin,C=Math.cos,clamp=(x,a,b)=>Math.max(a,Math.min(b,x)),fract=x=>x-Math.floor(x);let raster,rc,img,gl,gcanvas,program,ul;
function bg(c){const g=c.createRadialGradient(320,170,5,320,180,390);g.addColorStop(0,'#262048');g.addColorStop(1,'#040811');c.fillStyle=g;c.fillRect(0,0,640,360)}
function poly(c,p,color,stroke){c.beginPath();p.forEach((v,i)=>i?c.lineTo(...v):c.moveTo(...v));c.closePath();c.fillStyle=color;c.fill();if(stroke){c.strokeStyle=stroke;c.lineWidth=1;c.stroke()}}
function line(c,a,b,color,w=1){c.strokeStyle=color;c.lineWidth=w;c.beginPath();c.moveTo(...a);c.lineTo(...b);c.stroke()}
function hyper(c,t,pulse){bg(c);for(let shell=4;shell>=0;shell--){const vs=[];for(let i=0;i<16;i++){let v=[i&1?1:-1,i&2?1:-1,i&4?1:-1,i&8?1:-1];for(const [a,b,rate]of [[0,3,.7],[1,3,.43],[2,3,.31],[0,1,.18]]){const angle=t*rate+shell*.13,co=C(angle),si=S(angle),x=v[a];v[a]=x*co-v[b]*si;v[b]=x*si+v[b]*co}const f4=2.65/(3.1-v[3]),f3=(80+shell*20+pulse*4)/(3.4-v[2]*f4);vs.push([320+v[0]*f4*f3,172+v[1]*f4*f3,v[3]])}for(let i=0;i<16;i++)for(let axis=0;axis<4;axis++){let j=i^(1<<axis);if(j<i)continue;line(c,vs[i].slice(0,2),vs[j].slice(0,2),`hsla(${185+shell*27+axis*20},90%,${50+shell*7}%,${shell===4?.95:.26})`,shell===4?2:1)}if(shell===4)for(const v of vs){c.fillStyle='#f4f7ff';c.fillRect(v[0]-2,v[1]-2,4,4)}}
 for(let i=0;i<12;i++){const r=75+i*16,a=t*.15+i*.13;c.strokeStyle=`rgba(103,176,238,${.15-i*.009})`;c.beginPath();c.ellipse(320,172,r*1.4,r*.50,a,0,TAU);c.stroke()}}
function penroseShape(c,size,t){const a=[0,-1.2*size],b=[1.04*size,.6*size],d=[-1.04*size,.6*size],v=[a,b,d],width=size*.27;
 const beam=(j)=>{const p=v[j],q=v[(j+1)%3],dx=q[0]-p[0],dy=q[1]-p[1],len=Math.hypot(dx,dy),nx=-dy/len*width,ny=dx/len*width;const quad=[[p[0]+nx,p[1]+ny],[q[0]+nx,q[1]+ny],[q[0]-nx,q[1]-ny],[p[0]-nx,p[1]-ny]];poly(c,quad,['#aadfee','#de9bcf','#efd3a3'][j]);const half=[[p[0],p[1]],[q[0],q[1]],[q[0]-nx,q[1]-ny],[p[0]-nx,p[1]-ny]];poly(c,half,['#276c95','#6d357c','#916045'][j]);line(c,[p[0]+nx,p[1]+ny],[q[0]+nx,q[1]+ny],'#eeffff',2)};
 for(let j=0;j<3;j++)beam(j);
 // Cyclic occlusion: at each corner the outgoing beam is locally above the
 // incoming beam. There is no globally consistent 3D depth ordering.
 for(let j=0;j<3;j++){c.save();c.beginPath();c.arc(v[j][0],v[j][1],width*1.32,0,TAU);c.clip();beam(j);c.restore()}
 for(let i=0;i<9;i++){const s=fract(t*.18+i/9)*3,j=Math.floor(s),k=s-j,p=v[j],q=v[(j+1)%3];c.fillStyle='#fff7d4';c.shadowBlur=10;c.shadowColor='#fff6aa';c.fillRect(p[0]+(q[0]-p[0])*k-2,p[1]+(q[1]-p[1])*k-2,4,4);c.shadowBlur=0}}
function penrose(c,t,pulse){bg(c);for(let i=0;i<18;i++){const r=30+i*18;c.strokeStyle=`hsla(${260+i*4},70%,60%,.12)`;c.beginPath();c.ellipse(320,178,r*1.4,r*.64,t*.08,0,TAU);c.stroke()}c.save();c.translate(320,180);c.rotate(S(t*.3)*.17);penroseShape(c,107+pulse*3,t);c.restore();}
function portals(c,t,pulse){bg(c);const shift=fract(t*.38);for(let i=20;i>=0;i--){const depth=i+shift,scale=1.8*Math.pow(.79,depth),angle=depth*.14+t*.12;c.save();c.translate(320+S(depth*.45+t*.6)*12,177+C(depth*.3+t*.4)*12);c.rotate(angle);const w=270*scale,h=153*scale,wall=19*scale;c.fillStyle=`hsl(${235+depth*8+t*6},65%,${Math.max(6,28-depth*.8)}%)`;c.fillRect(-w-wall,-h-wall,2*(w+wall),wall);c.fillRect(-w-wall,h,2*(w+wall),wall);c.fillRect(-w-wall,-h,wall,2*h);c.fillRect(w,-h,wall,2*h);c.strokeStyle=`hsl(${178+depth*12},85%,${Math.max(28,80-depth*2)}%)`;c.lineWidth=Math.max(.6,2*scale);c.strokeRect(-w,-h,2*w,2*h);for(let j=0;j<4;j++){const a=j*PI/2+t;c.fillStyle='#ffe3b5';c.fillRect(C(a)*w*.8-2*scale,S(a)*h*.8-2*scale,4*scale,4*scale)}c.restore()}for(let i=0;i<9;i++){let a=i/9*TAU+t*.16,r=230;c.save();c.translate(320+C(a)*r,177+S(a)*r*.57);c.rotate(a+t*.1);c.globalAlpha=.12;penroseShape(c,12,t);c.restore()}}
const api={init(){},draw(c,which,t,local,pulse){if(which===0)hyper(c,local,pulse);else if(which===1)penrose(c,local,pulse);else portals(c,local,pulse)}};
if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.ImpossibleFX=api;
})(typeof window!=='undefined'?window:this);
