/* Four new finale effects. Original implementation of established mathematical
   constructions; Final bounded fractal: a recursively carved Menger sponge. */
(function(root){'use strict';
const PI=Math.PI,TAU=PI*2,S=Math.sin,C=Math.cos,clamp=(x,a,b)=>Math.max(a,Math.min(b,x)),fract=x=>x-Math.floor(x);let raster,rc,img,gl,gcanvas,program,ul;
function bg(c){const g=c.createRadialGradient(320,170,5,320,180,390);g.addColorStop(0,'#262048');g.addColorStop(1,'#040811');c.fillStyle=g;c.fillRect(0,0,640,360)}
function poly(c,p,color,stroke){c.beginPath();p.forEach((v,i)=>i?c.lineTo(...v):c.moveTo(...v));c.closePath();c.fillStyle=color;c.fill();if(stroke){c.strokeStyle=stroke;c.lineWidth=1;c.stroke()}}
function line(c,a,b,color,w=1){c.strokeStyle=color;c.lineWidth=w;c.beginPath();c.moveTo(...a);c.lineTo(...b);c.stroke()}
function hyper(c,t,pulse){bg(c);for(let shell=4;shell>=0;shell--){const vs=[];for(let i=0;i<16;i++){let v=[i&1?1:-1,i&2?1:-1,i&4?1:-1,i&8?1:-1];for(const [a,b,rate]of [[0,3,.7],[1,3,.43],[2,3,.31],[0,1,.18]]){const angle=t*rate+shell*.13,co=C(angle),si=S(angle),x=v[a];v[a]=x*co-v[b]*si;v[b]=x*si+v[b]*co}const f4=2.65/(3.1-v[3]),f3=(80+shell*20+pulse*4)/(3.4-v[2]*f4);vs.push([320+v[0]*f4*f3,172+v[1]*f4*f3,v[3]])}for(let i=0;i<16;i++)for(let axis=0;axis<4;axis++){let j=i^(1<<axis);if(j<i)continue;line(c,vs[i].slice(0,2),vs[j].slice(0,2),`hsla(${185+shell*27+axis*20},90%,${50+shell*7}%,${shell===4?.95:.26})`,shell===4?2:1)}if(shell===4)for(const v of vs){c.fillStyle='#f4f7ff';c.fillRect(v[0]-2,v[1]-2,4,4)}}
 for(let i=0;i<12;i++){const r=75+i*16,a=t*.15+i*.13;c.strokeStyle=`rgba(103,176,238,${.15-i*.009})`;c.beginPath();c.ellipse(320,172,r*1.4,r*.50,a,0,TAU);c.stroke()}}
function penroseShape(c,size,t){const a=[0,-1.2*size],b=[1.04*size,.6*size],d=[-1.04*size,.6*size],v=[a,b,d],width=size*.27;
 const beam=(j)=>{const p=v[j],q=v[(j+1)%3],dx=q[0]-p[0],dy=q[1]-p[1],len=Math.hypot(dx,dy),nx=-dy/len*width,ny=dx/len*width;const quad=[[p[0]+nx,p[1]+ny],[q[0]+nx,q[1]+ny],[q[0]-nx,q[1]-ny],[p[0]-nx,p[1]-ny]];poly(c,quad,['#aadfee','#de9bcf','#efd3a3'][j]);const half=[[p[0],p[1]],[q[0],q[1]],[q[0]-nx,q[1]-ny],[p[0]-nx,p[1]-ny]];poly(c,half,['#276c95','#6d357c','#916045'][j]);line(c,[p[0]+nx,p[1]+ny],[q[0]+nx,q[1]+ny],'#eeffff',2)};
 for(let j=0;j<3;j++)beam(j);
 // Cyclic occlusion: at each corner the outgoing beam is locally above the
 // incoming beam. There is no globally consistent 3D depth ordering.
 for(let j=0;j<3;j++){c.save();c.beginPath();c.arc(v[j][0],v[j][1],width*1.32,0,TAU);c.clip();beam(j);c.restore()}
 for(let i=0;i<9;i++){const s=fract(t*.18+i/9)*3,j=Math.floor(s),k=s-j,p=v[j],q=v[(j+1)%3];c.fillStyle='#fff7d4';c.shadowBlur=10;c.shadowColor='#fff6aa';c.fillRect(p[0]+(q[0]-p[0])*k-2,p[1]+(q[1]-p[1])*k-2,4,4);c.shadowBlur=0}}
function penrose(c,t,pulse){bg(c);for(let i=0;i<18;i++){const r=30+i*18;c.strokeStyle=`hsla(${260+i*4},70%,60%,.12)`;c.beginPath();c.ellipse(320,178,r*1.4,r*.64,t*.08,0,TAU);c.stroke()}c.save();c.translate(320,180);c.rotate(S(t*.3)*.17);penroseShape(c,107+pulse*3,t);c.restore();}
function portals(c,t,pulse){bg(c);const shift=fract(t*.38);for(let i=20;i>=0;i--){const depth=i+shift,scale=1.8*Math.pow(.79,depth),angle=depth*.14+t*.12;c.save();c.translate(320+S(depth*.45+t*.6)*12,177+C(depth*.3+t*.4)*12);c.rotate(angle);const w=270*scale,h=153*scale,wall=19*scale;c.fillStyle=`hsl(${235+depth*8+t*6},65%,${Math.max(6,28-depth*.8)}%)`;c.fillRect(-w-wall,-h-wall,2*(w+wall),wall);c.fillRect(-w-wall,h,2*(w+wall),wall);c.fillRect(-w-wall,-h,wall,2*h);c.fillRect(w,-h,wall,2*h);c.strokeStyle=`hsl(${178+depth*12},85%,${Math.max(28,80-depth*2)}%)`;c.lineWidth=Math.max(.6,2*scale);c.strokeRect(-w,-h,2*w,2*h);for(let j=0;j<4;j++){const a=j*PI/2+t;c.fillStyle='#ffe3b5';c.fillRect(C(a)*w*.8-2*scale,S(a)*h*.8-2*scale,4*scale,4*scale)}c.restore()}for(let i=0;i<9;i++){let a=i/9*TAU+t*.16,r=230;c.save();c.translate(320+C(a)*r,177+S(a)*r*.57);c.rotate(a+t*.1);c.globalAlpha=.12;penroseShape(c,12,t);c.restore()}}
function de(x,y,z){x/=1.5;y/=1.5;z/=1.5;let ax=Math.abs(x)-1,ay=Math.abs(y)-1,az=Math.abs(z)-1,d=Math.hypot(Math.max(ax,0),Math.max(ay,0),Math.max(az,0))+Math.min(Math.max(ax,ay,az),0),scale=1;for(let i=0;i<3;i++){const a=((x*scale)%2+2)%2-1,b=((y*scale)%2+2)%2-1,c=((z*scale)%2+2)%2-1;scale*=3;const rx=Math.abs(1-3*Math.abs(a)),ry=Math.abs(1-3*Math.abs(b)),rz=Math.abs(1-3*Math.abs(c));const hole=(Math.min(Math.max(rx,ry),Math.max(ry,rz),Math.max(rz,rx))-1)/scale;d=Math.max(d,hole)}return d*1.5}
function mandel(c,t,local){if(gl){gl.useProgram(program);gl.uniform1f(ul,local);gl.drawArrays(gl.TRIANGLES,0,3);c.imageSmoothingEnabled=false;c.drawImage(gcanvas,0,0,640,360);return}
 const w=224,h=126,ang=.35+local*.085,dist=4.8,ox=S(ang)*dist,oy=2.1,oz=C(ang)*dist,fl=Math.hypot(ox,oy,oz),fx=-ox/fl,fy=-oy/fl,fz=-oz/fl,rx=C(ang),rz=-S(ang),ux=-rz*fy,uy=rz*fx-rx*fz,uz=rx*fy,d=img.data;
 for(let yy=0;yy<h;yy++)for(let xx=0;xx<w;xx++){const u=(xx-w/2)/h*1.15,v=(yy-h/2)/h*1.15;let dx=fx+rx*u-ux*v,dy=fy-uy*v,dz=fz+rz*u-uz*v,n=Math.hypot(dx,dy,dz);dx/=n;dy/=n;dz/=n;let travel=0,steps=0,x=0,y=0,z=0,hit=false;for(;steps<64;steps++){x=ox+dx*travel;y=oy+dy*travel;z=oz+dz*travel;const sd=de(x,y,z);if(sd<.007){hit=true;break}travel+=Math.max(.004,sd*.82);if(travel>25)break}let red=5,green=9,blue=22;if(hit){const e=.006,base=de(x,y,z),nx=de(x+e,y,z)-base,ny=de(x,y+e,z)-base,nz=de(x,y,z+e)-base,nl=Math.hypot(nx,ny,nz)||1,light=clamp((nx*.4+ny*.7+nz*.6)/nl,0,1),ao=.42+.58*(1-steps/64),hue=.5+.5*S(y*1.1+x*.4+local*.3),spec=Math.pow(clamp((-dx*nx-dy*ny-dz*nz)/nl,0,1),12)*50;red=(48+125*hue)*(light*.8+.25)*ao+spec;green=(125+85*(1-hue))*(light*.8+.25)*ao+spec;blue=(175+65*hue)*(light*.8+.25)*ao+spec}else{const glow=Math.max(0,1-steps/64)*4;red+=glow;green+=glow;blue+=glow*2}const i=(yy*w+xx)*4;d[i]=red;d[i+1]=green;d[i+2]=blue;d[i+3]=255}rc.putImageData(img,0,0);c.imageSmoothingEnabled=false;c.drawImage(raster,0,0,640,360)}
const frag=`precision highp float;uniform float t;const float PI=3.14159265;
float de(vec3 p){p/=1.5;vec3 q=abs(p)-1.;float d=length(max(q,0.))+min(max(q.x,max(q.y,q.z)),0.),scale=1.;for(int i=0;i<3;i++){vec3 a=mod(p*scale,2.)-1.;scale*=3.;vec3 r=abs(1.-3.*abs(a));float hole=(min(max(r.x,r.y),min(max(r.y,r.z),max(r.z,r.x)))-1.)/scale;d=max(d,hole);}return d*1.5;}
void main(){vec2 uv=(gl_FragCoord.xy-vec2(224.,126.))/252.*1.15;float a=.35+t*.085,dist=4.8;vec3 ro=vec3(sin(a)*dist,2.1,cos(a)*dist),f=normalize(-ro),right=vec3(cos(a),0.,-sin(a)),up=cross(right,f),rd=normalize(f+right*uv.x+up*uv.y);float travel=0.;int n=0;bool hit=false;vec3 p;for(int i=0;i<64;i++){n=i;p=ro+rd*travel;float d=de(p);if(d<.007){hit=true;break;}travel+=max(.004,d*.82);if(travel>25.)break;}vec3 col=vec3(5.,9.,22.);if(hit){float e=.006,base=de(p);vec3 norm=normalize(vec3(de(p+vec3(e,0,0))-base,de(p+vec3(0,e,0))-base,de(p+vec3(0,0,e))-base));float li=max(0.,dot(norm,vec3(.4,.7,.6))),ao=.42+.58*(1.-float(n)/64.),hue=.5+.5*sin(p.y*1.1+p.x*.4+t*.3),sp=pow(max(0.,dot(-rd,norm)),12.)*50.;col=vec3(48.+125.*hue,125.+85.*(1.-hue),175.+65.*hue)*(li*.8+.25)*ao+sp;}gl_FragColor=vec4(col/255.,1.);}`;
function init(create){raster=create(224,126);rc=raster.getContext('2d');img=rc.createImageData(224,126);if(typeof window!=='undefined'){try{gcanvas=create(448,252);gl=gcanvas.getContext('webgl',{alpha:false,antialias:false,preserveDrawingBuffer:true});if(!gl)return;const shader=(type,src)=>{const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s};program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,'attribute vec2 a;void main(){gl_Position=vec4(a,0.,1.);}'));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,frag));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));gl.useProgram(program);const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,3,-1,-1,3]),gl.STATIC_DRAW);const at=gl.getAttribLocation(program,'a');gl.enableVertexAttribArray(at);gl.vertexAttribPointer(at,2,gl.FLOAT,false,0,0);ul=gl.getUniformLocation(program,'t');gl.viewport(0,0,448,252);}catch(e){console.warn('Fractal GPU fallback:',e.message);gl=null;}}}
const api={init,draw(c,which,t,local,pulse){if(which===0)hyper(c,local,pulse);else if(which===1)penrose(c,local,pulse);else if(which===2)portals(c,local,pulse);else mandel(c,t,local)}};
if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.ImpossibleFX=api;
})(typeof window!=='undefined'?window:this);
