'use strict';
const $=s=>document.querySelector(s),audio=$('#audio'),output=$('#output'),ctx=output.getContext('2d');ctx.imageSmoothingEnabled=false;audio.volume=.8;let score,ready=false,lastPattern=-1,lastRow=-1,lastPaint=-1;
const demo=RasterRitual.init({createCanvas:(w,h)=>{const el=document.createElement('canvas');el.width=w;el.height=h;return el},font:'ScenePixel'});
const format=t=>`${Math.floor(t/60)}:${String(Math.floor(t%60)).padStart(2,'0')}`;
function cell(v){if(!v.period)return '...';const nn=['C-','C#','D-','D#','E-','F-','F#','G-','G#','A-','A#','B-'];return nn[v.note%12]+(1+Math.floor(v.note/12))}
function updateTracker(t){if(!score)return;const p=Math.min(23,Math.floor(t/7.68)),row=Math.min(63,Math.floor((t-p*7.68)/.12));if(p===lastPattern&&row===lastRow)return;lastPattern=p;lastRow=row;$('#patNo').textContent='PATTERN '+p.toString(16).toUpperCase().padStart(2,'0');let html='';for(let d=-5;d<=6;d++){let r=row+d;html+='<span class="'+(d===0?'active':'row')+'">';if(r>=0&&r<64){html+=r.toString(16).toUpperCase().padStart(2,'0')+'  '+score.patterns[p][r].map(v=>cell(v)+' '+(v.sample?v.sample.toString(16).toUpperCase().padStart(2,'0'):'..')).join(' ')}else html+=' ';html+='</span>'}$('#pattern').innerHTML=html;$('#sceneTitle').textContent=`${String(p+1).padStart(2,'0')} / ${demo.names[p]}`;$('#effects').textContent=demo.families[p].join(' · ');$('#chapter').value=p;}
function paint(t){ctx.drawImage(demo.render(t),0,0);$('#seek').value=t;$('#clock').textContent=`${format(t)} / 3:04`;updateTracker(t)}
function loop(now){if(!audio.paused&&now-lastPaint>=18){paint(audio.currentTime);lastPaint=now}requestAnimationFrame(loop)}
async function toggle(){if(!ready)return;if(audio.paused){try{if(audio.currentTime>=demo.duration-.1)audio.currentTime=0;await audio.play();$('#cover').hidden=true;$('#play').textContent='Ⅱ PAUSE';$('#status').textContent='';}catch(e){$('#status').textContent='Could not start audio: '+e.message;}}else{audio.pause();$('#play').textContent='▶ PLAY'}}
function seek(t){audio.currentTime=Math.max(0,Math.min(demo.duration-.01,t));paint(audio.currentTime);$('#cover').hidden=true;}
async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await $('#screen').requestFullscreen()}catch(e){$('#status').textContent='Fullscreen unavailable: '+e.message}}
$('#start').onclick=toggle;$('#play').onclick=toggle;$('#restart').onclick=()=>seek(0);$('#seek').oninput=e=>seek(+e.target.value);$('#volume').oninput=e=>audio.volume=+e.target.value;$('#fullscreen').onclick=fullscreen;$('#chapter').onchange=e=>seek(+e.target.value*7.68+.24);audio.onended=()=>{$('#play').textContent='▶ REPLAY';paint(184.31)};audio.onerror=()=>$('#status').textContent='Could not load the soundtrack. Reload the page or check your connection.';
demo.names.forEach((n,i)=>{const o=document.createElement('option');o.value=i;o.textContent=`${String(i+1).padStart(2,'0')} / ${n}`;$('#chapter').append(o)});
document.addEventListener('keydown',e=>{if(['INPUT','SELECT','BUTTON'].includes(e.target.tagName))return;if(e.code==='Space'){e.preventDefault();toggle()}else if(e.code==='ArrowRight'){e.preventDefault();seek((Math.floor(audio.currentTime/7.68)+1)*7.68+.24)}else if(e.code==='ArrowLeft'){e.preventDefault();seek((Math.floor(audio.currentTime/7.68)-1)*7.68+.24)}else if(e.code==='KeyF')fullscreen()});
Promise.all([fetch('score.json').then(r=>{if(!r.ok)throw Error('score.json');return r.json()}),document.fonts.load('10px ScenePixel')]).then(([s])=>{score=s;ready=true;paint(3.84);$('#seek').value=0;$('#clock').textContent='0:00 / 3:04';$('#start').disabled=false;$('#start').textContent='▶ RUN THE DEMO';$('#play').disabled=false;requestAnimationFrame(loop)}).catch(e=>$('#status').textContent='Loading error: '+e.message);
